name: Build

on:
  push:
    branches:
      - fixing/issue-01
  workflow_dispatch:

jobs:

  hello-worls-job:
    name: Hello World
    runs-on: 'ubuntu-latest'
    steps:
      - name: Run echo
        run: |
          echo "Hello world.!"

      - name: Run ls
        run: |
          ls -la

  with-checkout-job:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run
        run: |
            sudo apt-get install -y tree
            tree .
      - name: Install Dependencies
        run: |
            sudo apt-get install -y python3 python3-pip
            tree .
      - name: Build package
        run: |
            pip install --upgrade build
            python -m build
            tree .